name: putty-gtk
version: '0.70+git' # Putty Version
summary: PuTTY is a free implementation of SSH and Telnet # 79 char long summary
description: |
  PuTTY is a client program for the SSH, Telnet and Rlogin network protocols. These protocols are all used to run a remote session on a computer, over a network. PuTTY implements the client end of that session: the end at which the session is displayed, rather than the end at which it runs.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: puTTY.svg
architectures:
  - amd64
  - i386

apps:

  putty:
    command: bin/putty
    desktop: usr/share/applications/putty.desktop
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
#      - media-hub
      - network-bind
      - network-manager
      - opengl
#      - optical-drive
#      - removable-media
      - unity7
      - x11

parts:
  enable-i386:
    plugin: nil
    prepare: |
      dpkg --add-architecture i386
      apt update

  desktopfile:
    source: snap/gui/
    plugin: dump
    organize:
      putty.desktop: usr/share/applications/putty.desktop
    
  putty:
    after: [enable-i386, desktop-gtk2]
      
    build-packages:
    - on i386:
      - zlib1g
      - libc6
      - libcanberra-gtk-module
      - libgdk-pixbuf2.0-0 
      - libglib2.0-0
      - libgtk2.0-0 
      - libpango-1.0-0
      - libx11-6
      - putty-tools
      - putty-doc
    - on amd64:
      - zlib1g
      - libc6
      - libcanberra-gtk-module:i386
      - libgdk-pixbuf2.0-0
      - gtk2-engines-pixbuf
      
      
    stage-packages:
    - on i386:
      - libcanberra-gtk-module
      - libgdk-pixbuf2.0-0
      - gtk2-engines-pixbuf
    - on amd64:
      - libcanberra-gtk-module:i386
      - libgdk-pixbuf2.0-0:i386
      - gtk2-engines-pixbuf
      
      
      
    source: https://the.earth.li/~sgtatham/putty/latest/putty-0.70.tar.gz
    plugin: autotools
#    after: [desktop-gtk2]
